# Generated by Django 4.1.7 on 2023-05-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="featured",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
