# Generated by Django 4.1.7 on 2023-05-17 19:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_post_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
